### ISSUE TITLE
Oper command fails

### ISSUE THREAD

**Issue by wiligl** [inspircd/docker#157]
Hi, I am using the official inspircd/inspircd docker image and I set an oper and hashed oper password with md5 (following the docker container tutorial). However, if I use the /oper commannd I get an "invalid credentials error".
My compose.yaml: https://pastebin.mozilla.org/miQ6r6Fp

However, if I *hardcode* the oper name and the hashed password in the opers.conf, the /oper command works fine.

It seems, there is something wrong with forwarding the environment variables from the compose.yaml to the opers.conf file.

PS: I know md5 is not recommended, same problem exists if I used sha256. I wanted to use an encryption method which gives a hashed password without special characters which need escaping.

**Comment by SadieCat** [comment]
The docker container does not load the MD5 module by default. It does however load the SHA256 module by default. Are you sure you didn't add it between tests?

This works for me:

```
services:
  ircd:
    image: inspircd/inspircd-docker
    container_name: ircd
    ports:
      - "6667:6667"
    restart: always
    environment:
      INSP_OPER_NAME: 'test'
      INSP_OPER_HASH: 'sha256'
      INSP_OPER_SSLONLY: 'no'
      INSP_OPER_PASSWORD_HASH: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08'
```
